### ISSUE TITLE
Sphinx 5 compatibility not specified

### ISSUE THREAD

**Issue by michaelosthege** [conda-forge/sphinx-jupyterbook-latex-feedstock#12]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I'm using `sphinx-jupyterbook-latex` in my thesis project, where locally I had manually upgraded to `sphinx==5.0.1` and `sphinx-jupyterbook-latex==0.5.1`.

However, my CI pipeline failed to create such an environment and I reproduced that problem with:

```bash
mamba create -c conda-forge -n jbtest "sphinx==5.0.1" "sphinx-jupyterbook-latex==0.5.1"
```

Which gave

```
Encountered problems while solving:
  - package sphinx-jupyterbook-latex-0.5.1-pyhd8ed1ab_0 requires sphinx >=3,<5, but none of the providers can be installed
```

In #11 I'm proposing to bump the upper limit, but the CI is failing and I can't see the error because Azure seems to be down.

@bollwyvl @AakashGfude is the current `<5` pin on purpose, or is incrementing the right call?

### Installed packages

```shell
does not apply
```

### Environment info

```shell
does not apply
```

**Comment by bollwyvl** [comment]
This now appears to work:

```bash
mamba create -c conda-forge -n jbtest --dry-run "sphinx==5.0.1" "sphinx-jupyterbook-latex==0.5.2"
```
